// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

// import "../styles/globals.css";
// import Header from "../components/header";
// import Sidebar from "../components/sidebar";
// import { ReactNode } from "react";
// import UserInitializer from "@/components/storecomponent/UserInitializer";
// import UserGroupMembershipInitializer from "@/components/storecomponent/UserGroupMembershipInitializer";
// //import GroupMembershipInitializer from "@/components/storecomponent/UserInitializer";
// //import GroupDropdown from "@/components/GroupDropdown";

// export default function RootLayout({ children }: { children: ReactNode }) {
//     return (
//         <html lang="ko" >
//             <body className="min-h-screen flex flex-col">
//                 <UserInitializer />
//                 <UserGroupMembershipInitializer />
//                 {/* <GroupMembershipInitializer /> */}
//                 <Header />
//                 <div className="flex flex-1">
//                     <Sidebar />
//                     <main className="flex-1 p-6 bg-gray-50 min-h-[calc(100vh-4rem)]">
//                         {children}
//                     </main>
//                 </div>
//             </body>
//         </html>
//     );
// }

import "../styles/globals.css";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import { ReactNode } from "react";
import UserInitializer from "@/components/storecomponent/UserInitializer";
import UserGroupMembershipInitializer from "@/components/storecomponent/UserGroupMembershipInitializer";

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="ko" className="h-full">
            <body className="h-screen flex flex-col  bg-white">
                <UserInitializer />
                <UserGroupMembershipInitializer />
                <Header />
                <div className="flex flex-1 overflow-hidden">
                    <Sidebar />
                    <main className="flex-1 overflow-y-auto">{children}</main>
                </div>
            </body>
        </html>
    );
}
